displayName=Farming Patch Advisor
author=Seadeadmeat
description=All things Farming: plan patches and compost runs, contracts, persistent timers, customizable runs, crop recommendations, and bank support
tags=farming,seed,patch,compost,bank,timer,checklist,highlight
version=1.10
plugins=com.farmingpatchadvisor.FarmingPatchAdvisorPlugin
build=standard
