displayName=Farming Patch Advisor
author=Seadeadmeat
description=All things Farming: plan every patch, contracts, persistent timers, customizable runs, crop recommendations, and bank support
tags=farming,seed,patch,bank,timer,checklist,highlight
version=1.2
plugins=com.farmingpatchadvisor.FarmingPatchAdvisorPlugin
build=standard
